---
title: "Homework20191925"
author: "Khó͘ Gē-Choân"
document: "html_document"
---

## 10.12

```{r}
n1=1100
p1=.47
m1=qnorm(1-0.05/2) ##mutiplier of 95% confidence level
p1+m1*sqrt(p1*(1-p1)/n1)
p1-m1*sqrt(p1*(1-p1)/n1)
##a. confidence intervel is 0.440 to 0.499

##b. 如果反覆進行抽樣，有95%的次數母體比例會被包含在0.440到0.499這個區間中。

```

## 10.22


```{r}
n.32=439
p.32=.3
##a.樣本比例p=0.3

##b.
sqrt(p.32*(1-p.32)/n.32) ## standard error

## c.
m.32=qnorm(1-0.05/2) ## mutiplier of 95% confidence interval

.3+ m.32*sqrt(p.32*(1-p.32)/n.32)
.3- m.32*sqrt(p.32*(1-p.32)/n.32)

## 95% confidence intervel is 0.342 to 0.257

## d.如果我們重複做這個抽樣調查，長期來看會有95%的調查的樣本比例加減margin of error的範圍有包含到母體比例。


```

## 10.34


```{r}
n.34=254
p.34=.33

## a.

sd.34=sqrt(p.34*(1-p.34)/n.34) ## standard error of the sample proportion

sd.34
## b.

m.34=qnorm(1-0.05/2) ## mutiplier of 95% confidence level

p.34+m.34*sd.34
p.34-m.34*sd.34

## 0.387 到0.272是95%信心水準下的信心區間。

## c. 

sqrt(p.34*(1-p.34)/n.34)## s.e of 90% confidence level
m.34c=qnorm(1-0.1/2)## mutiplier  of 90% confidence level

p.34+m.34c*sd.34
p.34-m.34c*sd.34
## 0.379到0.287 是90%信心水準下的信心區間

##d. 信心水準低的話，信賴區間就會比較小。信心水準90%代表如果重複相同的抽樣，有90%的抽樣結果所得到的信心區間會有包含到母體比例。



```



## 10.48


```{r}
n.48=501
## a. margin of error 是mutiplier*sqrt(p(1-p)/n)，保守估計是1/sqrt(n)，這裡n=500，1/sqrt(n) 大約就是5%。 
# mutiplier則是取95%信心水準下近似的2。
## b. 
p.48=.54
#sdandard error
sd.48=sqrt(p.48*(1-p.48)/n.48)

#mutiplier
m.48=qnorm(1-0.05/2)
#不過因為題目要求用5%的誤差範圍來算

p.48+0.05
p.48-0.05

## 95%的信賴區間是0.59到0.49。意思是說，如果重複做這個抽樣調查，有95%的抽樣到的區間會包含到母體比例（雖然每次抽樣得到的區間上下限會不同），母體比例也就是覺得自己和父母關係很好的美國青少年的比例。

## c.

p.48+m.48*sd.48
p.48-m.48*sd.48

## 從0.496到0.583是95%信心水準下的信心區間。相較於b的保守估計，區間的範圍會比較小一點。

## d
p.48d=0.05
sd.48d=sqrt(p.48d*(1-p.48d)/n.48)
sd.48d

p.48d+0.05
p.48d-0.05

p.48d+m.48*sd.48d
p.48d-m.48*sd.48d

## 用保守估計的話，95%信賴區間會是0到0.1。用公式算的話，則是0.03到0.069。區間的範圍會比保守估計小很多

## e. 因為保守估計其實就是p=0.5的時候得到的區間，p和0.5差越多，得到的區間就會越小

```


## 10.60

```{r}
n.52w=131
n.52m=61
p.52w=.611
p.52m=.426

sd.52=sqrt(p.52w*(1-p.52w)/n.52w+p.52m*(1-p.52m)/n.52m)
sd.52
m.99=qnorm(1-0.01/2) ## mutiplier of 99% confidence interval

p.52w-p.52m+m.99*sd.52
p.52w-p.52m-m.99*sd.52

## -0.011到0.381是99%信心水準下的信心區間。
## b. 相較於95%的信賴區間，99%的信賴區間要大上很多，因為99%的信賴區間包含了比95%的信賴區間更多的數值。


## c.會比較小。信賴區間的原理是重複抽樣的時候，每次抽樣得到的樣本平均值會呈現常態分佈，平均值等於母體參數。我們想求母體參數，但我們只能夠抽樣一次，但我們可以透過一次抽樣的樣本的標準差去估計重複抽樣的樣本分佈的標準差，而我們知道在常態分佈底下，我們能透過經驗法則知道有多少比例的觀察值會與平均值距離多少個標準差。求信賴區間的Mutiplier，就是用來換算要包含多少比例的觀察值需要多少個標準差，所以如果想包含90％的觀察值，就需要qnorm(1-0.9/2)個樣本的標準差。換句話說，我們抽樣得到的樣本統計量，90％的情況下會被包含在距離母體參數qnorm(1-0.9/2)的標準差的範圍內，反過來說就是抽樣的到的統計量有90%的情況會與母體參數距離qnorm(1-0.9/2)個標準差。調整信心水準，就是在調整想包含的觀察值的範圍，包含的觀察值越多就越可能包含到母體參數。

## d.99%的信賴區間下，女性願意因為人格而去跟另一人約會的比率相較於男生，高出了-0.011到0.381，有包含0，這代表兩者有可能相同，所以我們沒辦法下結論說女生因為人格而跟另一半約會的比率會比男生高。

```


## 10.66


```{r}
n.66m=524
n.66w=542
m.95=qnorm(1-0.05/2)
p.66m=0.14
p.66w=0.06

sd.66m=0.03/m.95
sd.66w=0.02/m.95

## a. 因為這兩個區間沒有重疊到，所以可以推論女性跟男性遇到睡眠呼吸問題的比例不同。

## b.

sd.p1p2=sqrt(p.66m*(1-p.66m)/n.66m+p.66w*(1-p.66w)/n.66w)
sd.p1p2
p.66m-p.66w+m.95*sd.p1p2
p.66m-p.66w-m.95*sd.p1p2

## 0.115到0.041是95%的信賴區間


## c.在95%的信賴區間下，兩個比例的差距並沒有包括到0。這代表說如果重複進行抽樣，95%的情況下的那一次抽樣得到的信賴區間有包含到兩個母體比例的差異。（每次抽樣得到的信賴區間上下限不同）。既然區間沒有包含到0(沒有差異)，我們可以有95%的信心去說男性和女性在睡眠呼吸問題上有差異。

```

