---
title: "20191113Homework"
author: "Khó͘ gē choân"
output: html_document
---

## 13.24

```{r}
library(knitr)
data.24=data.frame("Sex"=c("Women","Men"), "n"=c(35, 57), "Mean"=c(76.9, 70.42), "Standard Deviation"=c(11.6, 9.95))
kable(data.24)

##### a. ######

#檢定Penn State男性心跳的平均值是否是72

##1. 設定假設
#虛無假設：平均值等於72
#對立假設：平均值不等於72

##2.檢查條件並且找到適當的統計檢定量的值。
#因為樣本數足夠大，所以可以用t檢定。
#單一樣本求t檢定值的公式
#t=(x.bar-Mu.0)/s*sqrt(n)
t.24=abs((70.42-72)/9.95*sqrt(57))

#t=-1.198868     




##3.找到檢定p值
#因為對立假設是「不等於」，所以檢定是雙尾的，p值會是兩邊t分配底下距離虛無假設的平均值兩邊超過t值範圍的面積
#自由度是n-1
p.value.24=2*pt(t.24,df=56, lower.tail=F) 
p.value.24
#p 值等於0.2356278

##4.決定是否拒絕虛無假設
#設顯著水準alpha=.05, p值顯然大於顯著水準，代表我們不能夠拒絕虛無假設。


##5. 做出結論
#雖然抽樣的平均值不等於72，不過我們沒有足夠的信心拒絕平均值等於72的虛無假設。

##### b. #####
#測試Penn State婦女的心跳率平均值是否等於72

## 1. 設定假設
#虛無假設：Penn State 婦女的心跳率平均值等於72
#對立假設：Penn State 婦女的心跳率平均值不等於72

## 2. 檢查條件、找到適合的檢定統計量和檢定統計量的值
#因為樣本數夠大，所以可以進行t檢定

t.24b=abs((76.9-72)/11.6*sqrt(35))
t.24b


## 3.找到檢定的p值
#因為對立假設是「不等於」，所以檢定是雙尾的，p值會是t分配底下距離虛無假設的平均值超過t值範圍的面積。換句話說就是t分配底下，隨機變數和虛無假設平均值的距離大過於對立假設的平均值的機率。
#自由度是n-1
p.value24b=2*pt(t.24b, df=56, lower.tail=F)
p.value24b
#p值等於0.2356278 

## 4. 決定是否拒絕虛無假設
#設顯著水準alpha=.05, p值顯然大於顯著水準，代表我們不能夠拒絕虛無假設

## 5. 做出結論
# 我們沒有足夠的信心拒絕Penn State的女性心跳率的平均值等於72的虛無假設。


##### c. ######

# 雖然抽樣出來的平均值不管是男性或女性都不等於72，但因為抽樣是隨機的，每一次抽樣得到的結果都會略有不同，這個不同就是隨機變數的影響。透過統計，我們去判斷到底抽樣得到的數值和72這個值之間的距離有多少可能是隨機變數的影響？假設只有0.5%的信心水準可能是受到隨機變數的影響，代表說距離足夠大，大到只有在很低的機率下這個距離是隨機變數導致的，這時候我們就會認定平均值不等於72。但是因為最後算出來的距離可能受到隨機變數的影響的信心水準大於0.05，代表這個差異很可能是隨機變數導致的，我們就沒有辦法拒絕平均值等於72的假設。


```



## 13.44


```{r}
library("knitr")

data.44=data.frame("Volunteer Number"=as.integer(c(1:9)), "Placebo"=c(7,8,5,6,5,3,7,8,4), "Drug"=c(4,4,4,6,6,2,8,6,2))
differ=c(data.44$Placebo-data.44$Drug)
as.integer(differ)
data.44

## 1. 設定假設

# 虛無假設：服用藥的組別調整時差的時間的平均值等於服用安慰劑的組別
# 對立假設：服用藥的組別調整時差的時間的平均值等於服用安慰劑的組別

## 2. 檢查條件，找到適合的檢定統計量和算出檢定統計量的值
# 樣本數不夠大，所以要觀察有沒有呈現鐘形曲線
boxplot(differ)
# 有左右對稱，也沒有outlier或是左偏或右篇，因此可以用t檢定
head(data.44)
mean.d44=mean(differ)
mean.d44
sd.44=sqrt(1/8*sum((differ-mean.d44)^2))
sd.44

#兩個樣本、paired data的t檢定公式：t=(d.bar-0)/sd*sqrt(n)

t.44=(mean.d44-0)/sd.44*sqrt(9)


## 3. 找到檢定的p值

# 對立假設是服用藥的組別調整時差的時間的平均值等於服用安慰劑的組別，所以是單邊的檢定
# p值會是t分配底下，距離虛無假設平均值超過t值的範圍的面積
# 自由度是n-1
p.value44a=pt(t.44, df=8, lower.tail=F)
p.value44a

# 4. 決定是否拒絕虛無假設
# 我們設定顯著水準alpha=0.05，如果p值小於這個水準，代表我們有95%的信心認為抽樣統計量與虛無假設的距離不是因為隨機變數所導致的，反過來說，如果p值大於0.05，代表我們沒有足夠的信心認為抽樣統計量大於虛無假設的距離不是因為隨機變數所導致。
# 因為p值小於0.05，所以我們可以有足夠的信心去拒絕虛無假設


## 5. 做出結論
# 我們有足夠的信心拒絕虛無假設，也就是說我們有足夠的信心拒絕服用藥物的受試者的調整時差的時間和服用安慰劑的受試者調整時差的時間相等的假設。




```




## 13.62



## 13.64


## 13.76

## 13.78

2018年第二次期中考，所有考題。
• (1-1~1-5；2~4)
11/22，24:00前交。




